### ISSUE TITLE
Invalid prop `cancelButtonStyle`

### ISSUE THREAD

**Issue by valerioceniccola** [nicolas-van/react-bootstrap-confirmation#2]
There is a warning on console when the confirm dialog appears:

Warning: Failed prop type: Invalid prop `cancelButtonStyle` of value `secondary` supplied to `Confirmation`, expected one of ["primary","success","danger","warning","info","default"].
in Confirmation (created by _class)

Thank you.

**Comment by nicolas-van** [comment]
Was fixed, I'll publish a 1.0.4 as soon as possible.
